/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { BlockchainDatabaseService } from "../blockchainDatabase.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { BlockchainDatabaseCreateInput } from "./BlockchainDatabaseCreateInput";
import { BlockchainDatabase } from "./BlockchainDatabase";
import { BlockchainDatabaseFindManyArgs } from "./BlockchainDatabaseFindManyArgs";
import { BlockchainDatabaseWhereUniqueInput } from "./BlockchainDatabaseWhereUniqueInput";
import { BlockchainDatabaseUpdateInput } from "./BlockchainDatabaseUpdateInput";

@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class BlockchainDatabaseControllerBase {
  constructor(
    protected readonly service: BlockchainDatabaseService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}
  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Post()
  @swagger.ApiCreatedResponse({ type: BlockchainDatabase })
  @nestAccessControl.UseRoles({
    resource: "BlockchainDatabase",
    action: "create",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async createBlockchainDatabase(
    @common.Body() data: BlockchainDatabaseCreateInput
  ): Promise<BlockchainDatabase> {
    return await this.service.createBlockchainDatabase({
      data: data,
      select: {
        chainName: true,
        createdAt: true,
        creationDate: true,
        data: true,
        id: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get()
  @swagger.ApiOkResponse({ type: [BlockchainDatabase] })
  @ApiNestedQuery(BlockchainDatabaseFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "BlockchainDatabase",
    action: "read",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async blockchainDatabases(
    @common.Req() request: Request
  ): Promise<BlockchainDatabase[]> {
    const args = plainToClass(BlockchainDatabaseFindManyArgs, request.query);
    return this.service.blockchainDatabases({
      ...args,
      select: {
        chainName: true,
        createdAt: true,
        creationDate: true,
        data: true,
        id: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: BlockchainDatabase })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "BlockchainDatabase",
    action: "read",
    possession: "own",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async blockchainDatabase(
    @common.Param() params: BlockchainDatabaseWhereUniqueInput
  ): Promise<BlockchainDatabase | null> {
    const result = await this.service.blockchainDatabase({
      where: params,
      select: {
        chainName: true,
        createdAt: true,
        creationDate: true,
        data: true,
        id: true,
        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: BlockchainDatabase })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "BlockchainDatabase",
    action: "update",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async updateBlockchainDatabase(
    @common.Param() params: BlockchainDatabaseWhereUniqueInput,
    @common.Body() data: BlockchainDatabaseUpdateInput
  ): Promise<BlockchainDatabase | null> {
    try {
      return await this.service.updateBlockchainDatabase({
        where: params,
        data: data,
        select: {
          chainName: true,
          createdAt: true,
          creationDate: true,
          data: true,
          id: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: BlockchainDatabase })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "BlockchainDatabase",
    action: "delete",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async deleteBlockchainDatabase(
    @common.Param() params: BlockchainDatabaseWhereUniqueInput
  ): Promise<BlockchainDatabase | null> {
    try {
      return await this.service.deleteBlockchainDatabase({
        where: params,
        select: {
          chainName: true,
          createdAt: true,
          creationDate: true,
          data: true,
          id: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
