/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { CybersecurityEventService } from "../cybersecurityEvent.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { CybersecurityEventCreateInput } from "./CybersecurityEventCreateInput";
import { CybersecurityEvent } from "./CybersecurityEvent";
import { CybersecurityEventFindManyArgs } from "./CybersecurityEventFindManyArgs";
import { CybersecurityEventWhereUniqueInput } from "./CybersecurityEventWhereUniqueInput";
import { CybersecurityEventUpdateInput } from "./CybersecurityEventUpdateInput";

@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class CybersecurityEventControllerBase {
  constructor(
    protected readonly service: CybersecurityEventService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}
  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Post()
  @swagger.ApiCreatedResponse({ type: CybersecurityEvent })
  @nestAccessControl.UseRoles({
    resource: "CybersecurityEvent",
    action: "create",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async createCybersecurityEvent(
    @common.Body() data: CybersecurityEventCreateInput
  ): Promise<CybersecurityEvent> {
    return await this.service.createCybersecurityEvent({
      data: data,
      select: {
        createdAt: true,
        eventSeverity: true,
        eventTimestamp: true,
        eventType: true,
        id: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get()
  @swagger.ApiOkResponse({ type: [CybersecurityEvent] })
  @ApiNestedQuery(CybersecurityEventFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "CybersecurityEvent",
    action: "read",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async cybersecurityEvents(
    @common.Req() request: Request
  ): Promise<CybersecurityEvent[]> {
    const args = plainToClass(CybersecurityEventFindManyArgs, request.query);
    return this.service.cybersecurityEvents({
      ...args,
      select: {
        createdAt: true,
        eventSeverity: true,
        eventTimestamp: true,
        eventType: true,
        id: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: CybersecurityEvent })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "CybersecurityEvent",
    action: "read",
    possession: "own",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async cybersecurityEvent(
    @common.Param() params: CybersecurityEventWhereUniqueInput
  ): Promise<CybersecurityEvent | null> {
    const result = await this.service.cybersecurityEvent({
      where: params,
      select: {
        createdAt: true,
        eventSeverity: true,
        eventTimestamp: true,
        eventType: true,
        id: true,
        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: CybersecurityEvent })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "CybersecurityEvent",
    action: "update",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async updateCybersecurityEvent(
    @common.Param() params: CybersecurityEventWhereUniqueInput,
    @common.Body() data: CybersecurityEventUpdateInput
  ): Promise<CybersecurityEvent | null> {
    try {
      return await this.service.updateCybersecurityEvent({
        where: params,
        data: data,
        select: {
          createdAt: true,
          eventSeverity: true,
          eventTimestamp: true,
          eventType: true,
          id: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: CybersecurityEvent })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "CybersecurityEvent",
    action: "delete",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async deleteCybersecurityEvent(
    @common.Param() params: CybersecurityEventWhereUniqueInput
  ): Promise<CybersecurityEvent | null> {
    try {
      return await this.service.deleteCybersecurityEvent({
        where: params,
        select: {
          createdAt: true,
          eventSeverity: true,
          eventTimestamp: true,
          eventType: true,
          id: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
