/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { TrainingData } from "./TrainingData";
import { TrainingDataCountArgs } from "./TrainingDataCountArgs";
import { TrainingDataFindManyArgs } from "./TrainingDataFindManyArgs";
import { TrainingDataFindUniqueArgs } from "./TrainingDataFindUniqueArgs";
import { DeleteTrainingDataArgs } from "./DeleteTrainingDataArgs";
import { TrainingDataService } from "../trainingData.service";
@graphql.Resolver(() => TrainingData)
export class TrainingDataResolverBase {
  constructor(protected readonly service: TrainingDataService) {}

  async _trainingDataItemsMeta(
    @graphql.Args() args: TrainingDataCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @graphql.Query(() => [TrainingData])
  async trainingDataItems(
    @graphql.Args() args: TrainingDataFindManyArgs
  ): Promise<TrainingData[]> {
    return this.service.trainingDataItems(args);
  }

  @graphql.Query(() => TrainingData, { nullable: true })
  async trainingData(
    @graphql.Args() args: TrainingDataFindUniqueArgs
  ): Promise<TrainingData | null> {
    const result = await this.service.trainingData(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => TrainingData)
  async deleteTrainingData(
    @graphql.Args() args: DeleteTrainingDataArgs
  ): Promise<TrainingData | null> {
    try {
      return await this.service.deleteTrainingData(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
