/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import * as nestAccessControl from "nest-access-control";
import * as gqlACGuard from "../../auth/gqlAC.guard";
import { GqlDefaultAuthGuard } from "../../auth/gqlDefaultAuth.guard";
import * as common from "@nestjs/common";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { MachineLearningModel } from "./MachineLearningModel";
import { MachineLearningModelCountArgs } from "./MachineLearningModelCountArgs";
import { MachineLearningModelFindManyArgs } from "./MachineLearningModelFindManyArgs";
import { MachineLearningModelFindUniqueArgs } from "./MachineLearningModelFindUniqueArgs";
import { CreateMachineLearningModelArgs } from "./CreateMachineLearningModelArgs";
import { UpdateMachineLearningModelArgs } from "./UpdateMachineLearningModelArgs";
import { DeleteMachineLearningModelArgs } from "./DeleteMachineLearningModelArgs";
import { MachineLearningModelService } from "../machineLearningModel.service";
@common.UseGuards(GqlDefaultAuthGuard, gqlACGuard.GqlACGuard)
@graphql.Resolver(() => MachineLearningModel)
export class MachineLearningModelResolverBase {
  constructor(
    protected readonly service: MachineLearningModelService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @graphql.Query(() => MetaQueryPayload)
  @nestAccessControl.UseRoles({
    resource: "MachineLearningModel",
    action: "read",
    possession: "any",
  })
  async _machineLearningModelsMeta(
    @graphql.Args() args: MachineLearningModelCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => [MachineLearningModel])
  @nestAccessControl.UseRoles({
    resource: "MachineLearningModel",
    action: "read",
    possession: "any",
  })
  async machineLearningModels(
    @graphql.Args() args: MachineLearningModelFindManyArgs
  ): Promise<MachineLearningModel[]> {
    return this.service.machineLearningModels(args);
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => MachineLearningModel, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "MachineLearningModel",
    action: "read",
    possession: "own",
  })
  async machineLearningModel(
    @graphql.Args() args: MachineLearningModelFindUniqueArgs
  ): Promise<MachineLearningModel | null> {
    const result = await this.service.machineLearningModel(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @graphql.Mutation(() => MachineLearningModel)
  @nestAccessControl.UseRoles({
    resource: "MachineLearningModel",
    action: "create",
    possession: "any",
  })
  async createMachineLearningModel(
    @graphql.Args() args: CreateMachineLearningModelArgs
  ): Promise<MachineLearningModel> {
    return await this.service.createMachineLearningModel({
      ...args,
      data: args.data,
    });
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @graphql.Mutation(() => MachineLearningModel)
  @nestAccessControl.UseRoles({
    resource: "MachineLearningModel",
    action: "update",
    possession: "any",
  })
  async updateMachineLearningModel(
    @graphql.Args() args: UpdateMachineLearningModelArgs
  ): Promise<MachineLearningModel | null> {
    try {
      return await this.service.updateMachineLearningModel({
        ...args,
        data: args.data,
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => MachineLearningModel)
  @nestAccessControl.UseRoles({
    resource: "MachineLearningModel",
    action: "delete",
    possession: "any",
  })
  async deleteMachineLearningModel(
    @graphql.Args() args: DeleteMachineLearningModelArgs
  ): Promise<MachineLearningModel | null> {
    try {
      return await this.service.deleteMachineLearningModel(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
