/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { Metric } from "./Metric";
import { MetricCountArgs } from "./MetricCountArgs";
import { MetricFindManyArgs } from "./MetricFindManyArgs";
import { MetricFindUniqueArgs } from "./MetricFindUniqueArgs";
import { DeleteMetricArgs } from "./DeleteMetricArgs";
import { MetricService } from "../metric.service";
@graphql.Resolver(() => Metric)
export class MetricResolverBase {
  constructor(protected readonly service: MetricService) {}

  async _metricsMeta(
    @graphql.Args() args: MetricCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @graphql.Query(() => [Metric])
  async metrics(@graphql.Args() args: MetricFindManyArgs): Promise<Metric[]> {
    return this.service.metrics(args);
  }

  @graphql.Query(() => Metric, { nullable: true })
  async metric(
    @graphql.Args() args: MetricFindUniqueArgs
  ): Promise<Metric | null> {
    const result = await this.service.metric(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => Metric)
  async deleteMetric(
    @graphql.Args() args: DeleteMetricArgs
  ): Promise<Metric | null> {
    try {
      return await this.service.deleteMetric(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
