/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { IoTDeviceService } from "../ioTDevice.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { IoTDeviceCreateInput } from "./IoTDeviceCreateInput";
import { IoTDevice } from "./IoTDevice";
import { IoTDeviceFindManyArgs } from "./IoTDeviceFindManyArgs";
import { IoTDeviceWhereUniqueInput } from "./IoTDeviceWhereUniqueInput";
import { IoTDeviceUpdateInput } from "./IoTDeviceUpdateInput";

@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class IoTDeviceControllerBase {
  constructor(
    protected readonly service: IoTDeviceService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}
  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Post()
  @swagger.ApiCreatedResponse({ type: IoTDevice })
  @nestAccessControl.UseRoles({
    resource: "IoTDevice",
    action: "create",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async createIoTDevice(
    @common.Body() data: IoTDeviceCreateInput
  ): Promise<IoTDevice> {
    return await this.service.createIoTDevice({
      data: data,
      select: {
        createdAt: true,
        deviceName: true,
        deviceType: true,
        id: true,
        status: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get()
  @swagger.ApiOkResponse({ type: [IoTDevice] })
  @ApiNestedQuery(IoTDeviceFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "IoTDevice",
    action: "read",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async ioTDevices(@common.Req() request: Request): Promise<IoTDevice[]> {
    const args = plainToClass(IoTDeviceFindManyArgs, request.query);
    return this.service.ioTDevices({
      ...args,
      select: {
        createdAt: true,
        deviceName: true,
        deviceType: true,
        id: true,
        status: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: IoTDevice })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "IoTDevice",
    action: "read",
    possession: "own",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async ioTDevice(
    @common.Param() params: IoTDeviceWhereUniqueInput
  ): Promise<IoTDevice | null> {
    const result = await this.service.ioTDevice({
      where: params,
      select: {
        createdAt: true,
        deviceName: true,
        deviceType: true,
        id: true,
        status: true,
        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: IoTDevice })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "IoTDevice",
    action: "update",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async updateIoTDevice(
    @common.Param() params: IoTDeviceWhereUniqueInput,
    @common.Body() data: IoTDeviceUpdateInput
  ): Promise<IoTDevice | null> {
    try {
      return await this.service.updateIoTDevice({
        where: params,
        data: data,
        select: {
          createdAt: true,
          deviceName: true,
          deviceType: true,
          id: true,
          status: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: IoTDevice })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "IoTDevice",
    action: "delete",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async deleteIoTDevice(
    @common.Param() params: IoTDeviceWhereUniqueInput
  ): Promise<IoTDevice | null> {
    try {
      return await this.service.deleteIoTDevice({
        where: params,
        select: {
          createdAt: true,
          deviceName: true,
          deviceType: true,
          id: true,
          status: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
